### 所有 API 测试必须启动后端才能相应

### 健康检查
GET http://localhost:3001/api/health

### 内部用户注册
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "测试用户",
  "password": "123456",
  "department": "soft",
  "role": "internal"
}

### 外部用户注册
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "guest",
  "password": "123456",
  "department": "none",
  "role": "external"
}

### 管理员注册
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "administrator",
  "password": "qdezJDS",
  "department": "soft",
  "role": "admin"
}

### 用户登录
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "username": "testuser1",
  "password": "123456"
}